name: Deploy website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: ./_site # deploy src folder
